// <auto-generated />
using JobScout.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobScout.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JobScoutDbContext))]
    partial class JobScoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JobScout.Core.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CvBlob")
                        .HasColumnType("BLOB");

                    b.Property<string>("CvFileName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CvText")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CvUploadedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeRemote")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppConfig", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppConfig_SingleRow", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("JobScout.Core.Entities.ApplicationStatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ApplicationStatusChanges", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscoveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalisedName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.EmailCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("LastUid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailboxKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<uint?>("UidValidity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MailboxKey")
                        .IsUnique();

                    b.ToTable("EmailCheckpoints", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Industries", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobListingId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastEmailAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("JobListingId");

                    b.HasIndex("Status");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("FoundAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gaps")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PostedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SalaryKnown")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScoredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoredContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strengths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FoundAt");

                    b.HasIndex("Score");

                    b.HasIndex("Status");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("JobListings", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt");

                    b.ToTable("JobRunLogs", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.SuggestedStatusUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmailReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsResolved");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("SuggestedStatusUpdates", (string)null);
                });

            modelBuilder.Entity("JobScout.Core.Entities.ApplicationStatusChange", b =>
                {
                    b.HasOne("JobScout.Core.Entities.JobApplication", "JobApplication")
                        .WithMany("History")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobApplication", b =>
                {
                    b.HasOne("JobScout.Core.Entities.JobListing", "JobListing")
                        .WithMany()
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobListing", b =>
                {
                    b.HasOne("JobScout.Core.Entities.Company", "Company")
                        .WithMany("Listings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobScout.Core.Entities.SuggestedStatusUpdate", b =>
                {
                    b.HasOne("JobScout.Core.Entities.JobApplication", "JobApplication")
                        .WithMany("Suggestions")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("JobScout.Core.Entities.Company", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("JobScout.Core.Entities.JobApplication", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
